service: trc-rugby-club

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${self:service}-form-submissions-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-form-submissions-${self:provider.stage}

functions:
  submitForm:
    handler: api/submit-form/index.handler
    events:
      - http:
          path: submit-form
          method: post
          cors: true
      - http:
          path: submit-form
          method: options
          cors: true
    package:
      individually: true
      patterns:
        - 'api/submit-form/**'

resources:
  Resources:
    FormSubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-form-submissions-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: timestamp-index
            KeySchema:
              - AttributeName: timestamp
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
